name: flashbyte
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  android_intent_plus: ^6.0.0
  external_path: ^2.2.0
  fast_file_picker: ^0.4.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  heroine: ^0.5.0+2
  loading_indicator_m3e: ^0.1.1
  material_new_shapes: ^1.0.0
  mime: ^2.0.0
  mobile_scanner: ^7.0.1
  motor: ^1.0.1
  ns_file_coordinator_util: ^0.25.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  process_run: ^1.2.4
  qr_flutter: ^4.1.0
  saf_util: ^0.10.0
  uri_to_file: ^1.0.0
  uuid: ^4.5.1
  widget_zoom: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
